apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: behaviosec-proxy-app
  name: behaviosec-proxy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: behaviosec-proxy-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: behaviosec-proxy-app
    spec:
      containers:
      - image: localhost:5000/apps/proxy
        name: demo
        resources: {}
        readinessProbe:
          httpGet:
            port: 9090
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 9090
            path: /actuator/health/liveness
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 10" ]
status: {}
