apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: behaviosec-proxy-app
  name: behaviosec-proxy-app
spec:
  ports:
  - name: 90-9090
    port: 90
    protocol: TCP
    targetPort: 9090
  selector:
    app: behaviosec-proxy-app
  type: LoadBalancer
status:
  loadBalancer: {}
