apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: proxyapp
images:
  - name: apps/proxy
    newName: localhost:5000/apps/proxy
resources:
- deployment.yaml
transformers:
- github.com/dsyer/docker-services/layers/actuator?ref=HEAD
